name: Release
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          # TODO: Windows
          # - runner: windows-latest
          #   os: windows
          #   arch: x86_64
          # MacOS
          - runner: macos-latest
            os: macos
            arch: x86_64
          - runner: macos-latest
            os: macos
            arch: aarch64
          # Linux
          - runner: ubuntu-latest
            os: linux
            arch: x86_64
          - runner: ubuntu-latest
            os: linux
            arch: aarch64
      fail-fast: false
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: zig build --summary all -Doptimize=ReleaseFast -Dtarget=${{matrix.arch}}-${{matrix.os}}
      - uses: vimtor/action-zip@v1.2
        with:
          files: zig-out/bin/bun zig-out/bin/bunx zig-out/bin/bunv
          dest: bunv-${{matrix.os}}-${{matrix.arch}}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: bunv-${{matrix.os}}-${{matrix.arch}}
          path: "*.zip"
          if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
          merge-multiple: true
      - run: ls -R
