on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: action/checkout@4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - if: matrix.os == 'macos-latest'
        run: |
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=aarch64-macos
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=x86_64-macos

      - if: matrix.os == 'ubuntu-latest'
        run: |
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=aarch64-linux
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=x86_64-linux

      - if: matrix.os == 'windows-latest'
        run: |
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=x86_64-windows

      - run: ls zig-out/bin
