name: Release
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  # TODO: Add validation workflow
  # validate:
  #   uses: ./.github/workflows/validate.yml
  #   secrets: inherit
  #
  build:
    uses: ./.github/workflows/build-platforms.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          path: zig-out
          merge-multiple: true
      - id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          release-count: 0
          skip-on-empty: false
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: "zig-out/*.zip"
          make_latest: true
