name: Release
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # TODO: Windows support
          # - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: |
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=aarch64-macos
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=x86_64-macos
        if: matrix.os == 'macos-latest'
      - run: |
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=aarch64-linux
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=x86_64-linux
        if: matrix.os == 'ubuntu-latest'
      - run: |
          zig build --summary all -Doptimize=ReleaseFast -Dtarget=x86_64-windows
        if: matrix.os == 'windows-latest'
      - run: ls zig-out/bin
